In [ ]:
import pandas as pd
df= pd.read_csv("kaggleDATA.csv")
df
# df.describe()

,Id,Date,Time,CO2_(dinning-room),CO2_room,Relative_humidity_(dinning-room),Relative_humidity_room,Lighting_(dinning-room),Lighting_room,Meteo_Rain,Meteo_Sun_dusk,Meteo_Wind,Meteo_Sun_light_in_west_facade,Meteo_Sun_light_in_east_facade,Meteo_Sun_light_in_south_facade,Meteo_Sun_irradiance,Outdoor_relative_humidity_Sensor,Day_of_the_week,Indoor_temperature_room
0,0,13/03/2012,11:45,216.560,221.920,39.9125,42.4150,81.6650,113.5200,0.0,623.360,1.426250,9690.24,12604.20,95436.800,758.8800,48.3750,2.0,17.8275
1,1,13/03/2012,12:00,219.947,220.363,39.9267,42.2453,81.7413,113.6050,0.0,623.211,1.592000,11022.00,10787.20,95436.800,762.0690,47.8080,2.0,18.1207
2,2,13/03/2012,12:15,219.403,218.933,39.7720,42.2267,81.4240,113.6000,0.0,622.656,1.891330,13960.50,9669.63,95398.600,766.2510,47.4320,2.0,18.4367
3,3,13/03/2012,12:30,218.613,217.045,39.7760,42.0987,81.5013,113.3440,0.0,622.571,1.828000,18511.20,9648.13,95360.300,766.0370,47.0240,2.0,18.7513
4,4,13/03/2012,12:45,217.714,216.080,39.7757,42.0686,81.4657,113.0340,0.0,622.400,2.360710,26349.00,9208.32,95354.900,762.7430,45.4743,2.0,19.0414
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2759,2759,11/04/2012,05:30,190.539,192.181,41.3120,41.6880,11.4427,12.9400,0.0,392.603,0.074667,0.00,0.00,0.000,-3.4340,49.2960,3.0,20.8187
2760,2760,11/04/2012,05:45,190.421,193.067,41.3173,41.7200,11.6867,19.3200,0.0,613.120,0.000000,465.92,2716.67,523.264,3.8520,50.0373,3.0,20.7053
2761,2761,11/04/2012,06:00,190.432,193.653,41.3333,41.7573,19.5387,23.2427,0.0,613.803,0.310667,3454.98,16203.80,3347.460,26.8300,50.0587,3.0,20.5827
2762,2762,11/04/2012,06:15,191.531,193.387,41.3093,41.8107,20.9853,23.4400,0.0,615.403,0.299333,6795.26,38303.10,7110.660,66.9493,49.8400,3.0,20.5200
2763,2763,11/04/2012,06:30,191.563,193.664,41.2800,41.8373,20.5620,22.3080,0.0,616.725,0.908000,8952.83,51347.50,10270.700,112.2670,50.2987,3.0,20.4400

In [5]:
df1 = df.drop(columns=["CO2_(dinning-room)", "Relative_humidity_(dinning-room)", "Lighting_(dinning-room)", "Lighting_room", "Meteo_Rain", "Meteo_Sun_dusk", "Meteo_Sun_light_in_west_facade", "Meteo_Sun_light_in_east_facade", "Meteo_Sun_light_in_south_facade", "Meteo_Sun_irradiance"])
df1

,Id,Date,Time,CO2_room,Relative_humidity_room,Meteo_Wind,Outdoor_relative_humidity_Sensor,Day_of_the_week,Indoor_temperature_room
0,0,13/03/2012,11:45,221.920,42.4150,1.426250,48.3750,2.0,17.8275
1,1,13/03/2012,12:00,220.363,42.2453,1.592000,47.8080,2.0,18.1207
2,2,13/03/2012,12:15,218.933,42.2267,1.891330,47.4320,2.0,18.4367
3,3,13/03/2012,12:30,217.045,42.0987,1.828000,47.0240,2.0,18.7513
4,4,13/03/2012,12:45,216.080,42.0686,2.360710,45.4743,2.0,19.0414
...,...,...,...,...,...,...,...,...,...
2759,2759,11/04/2012,05:30,192.181,41.6880,0.074667,49.2960,3.0,20.8187
2760,2760,11/04/2012,05:45,193.067,41.7200,0.000000,50.0373,3.0,20.7053
2761,2761,11/04/2012,06:00,193.653,41.7573,0.310667,50.0587,3.0,20.5827
2762,2762,11/04/2012,06:15,193.387,41.8107,0.299333,49.8400,3.0,20.5200
2763,2763,11/04/2012,06:30,193.664,41.8373,0.908000,50.2987,3.0,20.4400

In [3]:
import pandas as pd
import numpy as np

# Define column names
columns = ["Timestamp", "Temperature (°C)", "Humidity (%)", "Moisture Level (%)", "Gas Level (PPM)"]

# Generate timestamps for 4 hours
timestamps = pd.date_range(start="2025-03-06 08:00:00", periods=4, freq="H")

# Manually adjust values so that the first three hours are predicted as "Safe" and the fourth hour as "Risky"
data = {
    "Timestamp": timestamps,
    "Temperature (°C)": [25, 26, 24, 35],  # Increase in the 4th hour
    "Humidity (%)": [55, 58, 53, 80],  # Sharp rise in humidity in 4th hour
    "Moisture Level (%)": [12, 13, 11, 25],  # High moisture level in 4th hour
    "Gas Level (PPM)": [120, 125, 110, 300]  # Sudden spike in gas levels
}

# Convert to DataFrame
df = pd.DataFrame(data)

# Save the new dataset to CSV
df.to_csv("generated_grain_storage.csv", index=False)

print("✅ New dataset generated and saved as 'generated_grain_storage.csv' successfully!")

✅ New dataset generated and saved as 'generated_grain_storage.csv' successfully!

C:\Users\ASUS\AppData\Local\Temp\ipykernel_24976\2319615615.py:8: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  timestamps = pd.date_range(start="2025-03-06 08:00:00", periods=4, freq="H")